-- ==============================================================================
-- 0. DROP EXISTING OBJECTS
-- ==============================================================================
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS cart_items CASCADE;
DROP TABLE IF EXISTS carts CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS product_stocks CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS authen CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP TYPE IF EXISTS order_status;
DROP TYPE IF EXISTS color;
DROP TYPE IF EXISTS item_size;

CREATE TYPE item_size AS ENUM ('S', 'M', 'L', 'XL', 'XXL');
CREATE TYPE color as ENUM ('Red', 'Green', 'Blue');
CREATE TYPE order_status as ENUM ('pending', 'checkout', 'completed', 'cancelled');

-- 1. Users
CREATE TABLE users (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1),
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    avatar VARCHAR(255),
    contact VARCHAR(20),
    address VARCHAR(255),
    description TEXT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Authen
CREATE TABLE authen (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    user_id INT UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    username VARCHAR(50) UNIQUE,
    email VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

-- 3. Products
CREATE TABLE products (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    title VARCHAR(100) NOT NULL,
    description TEXT,
    rating DECIMAL(2, 1) DEFAULT 0,
    num_reviews INT NOT NULL DEFAULT 0,
    image VARCHAR(255),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. Product Stocks
CREATE TABLE product_stocks (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    product_id INT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    size item_size NOT NULL,
    color color NOT NULL,
    original_price DECIMAL(10, 2) NOT NULL,
    promotion_price DECIMAL(10, 2),
    stock INT NOT NULL DEFAULT 0,
    UNIQUE (product_id, size, color)
);

-- 5. Comments
CREATE TABLE comments (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    product_id INT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 6. Carts
CREATE TABLE carts (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    user_id INT UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 7. Cart Items
CREATE TABLE cart_items (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    cart_id INT NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
    stock_id INT NOT NULL REFERENCES product_stocks(id) ON DELETE CASCADE,
    quantity INT NOT NULL DEFAULT 1,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (cart_id, stock_id)
);

-- 8. Orders
CREATE TABLE orders (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status order_status NOT NULL DEFAULT 'pending',
    subtotal DECIMAL(10, 2) NOT NULL DEFAULT 0,
    discount DECIMAL(10, 2) NOT NULL DEFAULT 0,
    delivery_fee DECIMAL(10, 2) NOT NULL DEFAULT 0,
    total DECIMAL(10, 2) GENERATED ALWAYS AS (subtotal - discount + delivery_fee) STORED,
    promo_code VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 9. Order Items
CREATE TABLE order_items (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    order_id INT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    stock_id INT REFERENCES product_stocks(id) ON DELETE SET NULL,
    title VARCHAR(100) NOT NULL,
    image VARCHAR(255),
    quantity INT NOT NULL DEFAULT 1,
    price_at_purchase DECIMAL(10, 2) NOT NULL,
    total_price DECIMAL(10, 2) GENERATED ALWAYS AS (price_at_purchase * quantity) STORED,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
