CREATE TYPE item_size AS ENUM ('S', 'M', 'L', 'XL', 'XXL');
CREATE TYPE color as ENUM ('Red', 'Green', 'Blue', 'Rainbow', 'Black', 'White', 'Grey');
CREATE TYPE order_status as ENUM ('cart', 'completed', 'checkout');

-- 1. Users
CREATE TABLE users (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 INCREMENT BY 1),
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    avatar VARCHAR(255),
    description TEXT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Products
CREATE TABLE products (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    title VARCHAR(100) NOT NULL,
    description TEXT,
    original_price DECIMAL(10, 2) NOT NULL,
    promotion_price DECIMAL(10, 2),
    discount DECIMAL(5, 2) GENERATED ALWAYS AS (
        CASE
            WHEN promotion_price IS NULL THEN NULL
            ELSE ROUND((original_price - promotion_price) / original_price * 100, 2)
        END
    ) STORED,
    rating DECIMAL(2, 1) DEFAULT 0,
    num_reviews INT NOT NULL DEFAULT 0,
    image VARCHAR(255),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Comments
CREATE TABLE comments (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    product_id INT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. Orders
CREATE TABLE orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id INT REFERENCES users(id) ON DELETE CASCADE,
    status order_status DEFAULT 'cart',
    subtotal DECIMAL(10, 2) NOT NULL DEFAULT 0,
    discount DECIMAL(10, 2) NOT NULL DEFAULT 0,
    delivery_fee DECIMAL(10, 2) NOT NULL DEFAULT 0,
    total DECIMAL(10, 2) GENERATED ALWAYS AS (subtotal - discount + delivery_fee) STORED,
    promo_code VARCHAR(20),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 5. Order Items
CREATE TABLE order_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id UUID REFERENCES orders(id) ON DELETE CASCADE,
    product_id INT REFERENCES products(id) ON DELETE CASCADE,
    size item_size NOT NULL,
    color color NOT NULL,
    quantity INT DEFAULT 1 NOT NULL,
    unit_price DECIMAL(10, 2) NOT NULL,
    total_price DECIMAL(10, 2) GENERATED ALWAYS AS (unit_price * quantity) STORED,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (order_id, product_id, size, color)
);